# This is a config for E2B sandbox template.
# You can use template ID (sm3r39vktkmu37lna0qa) or template name (capsule-expo-sandbox) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("capsule-expo-sandbox") # Sync sandbox
# sandbox = await AsyncSandbox.create("capsule-expo-sandbox") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('capsule-expo-sandbox')

team_id = "ca97f034-46fd-4f61-96f8-a31147b4e6eb"
memory_mb = 4_096
cpu_count = 4
dockerfile = "templates/expo-template/e2b.Dockerfile"
template_name = "capsule-expo-sandbox"
template_id = "sm3r39vktkmu37lna0qa"
