# This is a config for E2B sandbox template.
# You can use template ID (xzfs8fvtvpe3tcqgyyrp) or template name (github) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("github") # Sync sandbox
# sandbox = await AsyncSandbox.create("github") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('github')

team_id = "ca97f034-46fd-4f61-96f8-a31147b4e6eb"
memory_mb = 4_096
cpu_count = 4
start_cmd = "tail -f /dev/null"
dockerfile = "templates/github-template/e2b.Dockerfile"
template_name = "github"
template_id = "xzfs8fvtvpe3tcqgyyrp"
